### ISSUE TITLE
More examples of commands and output for ocelot client to verify installation + configuration

### ISSUE THREAD

**Issue by tjtelan** [level11consulting/ocelot#185]
In the wiki, on the Client page, we go from Installation, straight into vcs configuration.
https://github.com/level11consulting/ocelot/wiki/client

Our local users get confused about setting up vcs when they don't need to, despite the existing block of text informing them that it's been set up. (But admittedly it's really easy to overlook, and could benefit from a more eye-catching header.)

However, the root of the trap is they are confused about what the next step is. The priority for the client should be the ocelot.yml, and instead, the docs quickly take training wheels off and focus on configuring vcs.

I think we can break this pattern up by giving some examples of commands to run, and what we expect as output. Both as a developer and as a user plugging into an existing Ocelot instance. And instead, we can introduce another important sync point where we verify that installation is working as expected.

**Comment by eccramer** [comment]
I think this would help a lot, and also allow us to have two major "tracks" of setup steps, one for users taking advantage of an already setup Ocelot instance, and one for someone setting up a local development environment. On the user track, it will be more around "Create ocelot.yml -> check it in -> ocelot build -> ocelot summary" and on the developer side it will be around the workflow "checkout ocelot code -> vagrant up -> start admin/hookhandler/werker -> setup vcs credentials -> run example ocelot build"

**Comment by tjtelan** [comment]
Yep! LGTM

**Comment by eccramer** [comment]
Cool! Thanks T.J.

Closing
