### ISSUE TITLE
Document adding github repos to Ocelot

### ISSUE THREAD

**Issue by eccramer** [level11consulting/ocelot#191]
Documentation of adding Bitbucket credentials to ocelot, and setting up Oauth on the Bitbucket side exist. However, there doesn't seem to be any documentation of the same process for Github.

We need to figure that out and write it down.

**Comment by tjtelan** [comment]
Closing by addition of https://github.com/level11consulting/ocelot/wiki/client#to-add-a-new-consumer-for-a-github-account
