### ISSUE TITLE
how to know precisely which repos are tracked by ocelot

### ISSUE THREAD

**Issue by shankj3** [level11consulting/ocelot#24]
right now it's kinda hacky, it is whatever is in te poll table list, then for webhooks it would just be whatever has been written to the database. it is by no means robust. 
maybe we will need to just add a simple table that will be kept up to date by add/remove commands

**Comment by tjtelan** [comment]
This has been added, but I'm not sure what version introduced it.

`ocelot repos list` is the command to answer this question.

It displays (account, repo, datetime last queued)
